name: Daily Commit Workflow

permissions:
  contents: write

on:
  schedule:
    - cron: '50 17 * * *'  # 11:15 PM IST (5:45 PM UTC)
  workflow_dispatch:

jobs:
  daily-commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: 23f2005144@ds.study.iitm.ac.in - Update file
        run: |
          echo "Last updated on $(date)" >> daily-log.txt

      - name: Commit and Push Changes
        run: |
          git config user.name "GitHub Action Bot"
          git config user.email "23f2005144@ds.study.iitm.ac.in"
          git add daily-log.txt
          git commit -m "Automated daily commit" || echo "No changes to commit"
          git push
